// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZbdbSG63PjrSUKQHI6QtWIyOrpWI9f_U',
    appId: '1:705249545237:android:5e7b3b09dec9dd8814521c',
    messagingSenderId: '705249545237',
    projectId: 'fir-login-bb349',
    storageBucket: 'fir-login-bb349.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD20Ju2iiNPXq_ysTrvf7R_-v0dF0iole8',
    appId: '1:705249545237:ios:ceaa88e160ee659114521c',
    messagingSenderId: '705249545237',
    projectId: 'fir-login-bb349',
    storageBucket: 'fir-login-bb349.appspot.com',
    iosClientId: '705249545237-hah6g03uu9qn8k04jclfjd1nfif88ie0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD20Ju2iiNPXq_ysTrvf7R_-v0dF0iole8',
    appId: '1:705249545237:ios:ceaa88e160ee659114521c',
    messagingSenderId: '705249545237',
    projectId: 'fir-login-bb349',
    storageBucket: 'fir-login-bb349.appspot.com',
    iosClientId: '705249545237-hah6g03uu9qn8k04jclfjd1nfif88ie0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin',
  );
}
