// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkBaQs0da79X66aHAyEQISJugyJ3BrBZQ',
    appId: '1:248146055409:web:e42ac45352f1a8d24d1950',
    messagingSenderId: '248146055409',
    projectId: 'fir-demo-7475c',
    authDomain: 'fir-demo-7475c.firebaseapp.com',
    storageBucket: 'fir-demo-7475c.appspot.com',
    measurementId: 'G-642MLDHB07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH61BmcRNFm__tljvvb1Vs26W5wKbX3_0',
    appId: '1:248146055409:android:ea114695a573b0e94d1950',
    messagingSenderId: '248146055409',
    projectId: 'fir-demo-7475c',
    storageBucket: 'fir-demo-7475c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhnur7VthhvpFiFC6i8ymnmjzkwemPNV0',
    appId: '1:248146055409:ios:844fef598b684e3e4d1950',
    messagingSenderId: '248146055409',
    projectId: 'fir-demo-7475c',
    storageBucket: 'fir-demo-7475c.appspot.com',
    iosClientId: '248146055409-1hl6r9mar76b4qhflrdm1acnq910m2ga.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );
}
